name: Tests

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               xvfb-run -a yarn test
          elif [ "$RUNNER_OS" == "Windows" ]; then
               yarn test
          elif
               [ "$RUNNER_OS" == "macOS" ]; then
               yarn test:coverage
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
