name: Release
on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install the dependencies
        run: yarn install --frozen-lockfile

      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
